name: HACS Validation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: HACS Validation
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: "integration"
